### PR TITLE
Fix add_phylopic_tree and use it in the base R vignette

### LINKED ISSUE #113: Update base R vignette with `add_phylopic_tree()`
With the addition of `add_phylopic_tree()` in #110, we should update the base R vignette to showcase this new function instead of the manual example we have now.

### PR DESCRIPTION
**Pull request by willgearty**
This does the following:

- Fix `add_phylopic_tree()` to work on phylogenies with fossil tips by extracting the x coordinates from the `last_plot.phylo` environment. Because the x coordinate is no longer tied to the width of the silhouette, `add_phylopic_tree()` now also works when a `height` value is specified.
- As part of the above change, I've also inverted the behavior of the padding for `add_phylopic_tree()` such that it pads the silhouette away from the tip (instead of away from the edge of the plot). I've updated the docs, tests, and test snapshots accordingly.
- Various clean up of the docs for `add_phylopic_tree()`
- Replaces `add_phylopic_base()` with `add_phylopic_tree()` in the phylogeny example in the base R vignette. Fixes #113.

### CODE REVIEW

**Comment by willgearty** [comment]
@ms609 I'd really appreciate it if you took a quick look at this, too, since you wrote the original function.

**Comment by willgearty** [comment]
Hmm...no, I hadn't thought of that use case (in my mind the silhouettes should always be near their respective tips). I'll think about  how to allow for both behaviors...

**Comment by willgearty** [comment]
OK, the latest commit allows for users to specify `align = "plot"` to align the silhouettes along the plot edge like the old behavior. Thanks for flagging that use case @ms609!

**Comment by willgearty** [comment]
@ms609 Would you be able to fully review this? I'm hoping to include it in a patch release on CRAN soon.

File: R/add_phylopic_tree.R [hunk 1]
```diff
@@ -6,26 +6,35 @@
...
+#'   at the x coordinate of the respective tip, plus any horizontal padding
+#'   specified by `padding` or `relPadding`. If `"plot"` is specified, the
+#'   silhouette is placed at the right-hand side of the plotting area,
+#'   determined by `par("usr")`, plus any horizontal padding specified by
+#'   `padding` or `relPadding`.
+#' @param width,relWidth The width of each silhouette, in the plot coordinate
+#'   system (`width`) or relative to the size of the plotting area (`relWidth`).
+#'   If "NULL" and `height` is specified, the width is determined by the aspect
+#'   ratio of the original image. One of height and width must be "NULL".
+#' @param padding,relPadding Horizontal padding for each silhouette from it's
```
Comment (ms609) [inline R/add_phylopic_tree.R]: For consistency, specify type (and catch typo)
```suggestion
#' @param padding,relPadding `numeric`. Horizontal padding for each silhouette from its
```

File: R/add_phylopic_tree.R [hunk 2]
```diff
@@ -6,26 +6,35 @@
...
-#' edge of the plotting area,
-#' in the plot coordinate system (`padding`) or
-#' relative to the size of the plotting area (`relPadding`).
-#' Negative values offset to the right.
-#' @param \dots Further arguments to pass to `add_phylopic_base()`.
-#' @author [Martin R. Smith](https://orcid.org/0000-0001-5660-1727) 
-#' (<martin.smith@durham.ac.uk>)
-#' @seealso
-#' For trees plotted using \pkg{ggtree}, see [`geom_phylopic()`].
+#' @param tree The phylogenetic tree object of class `phylo` on which to add the
```
Comment (ms609) [inline R/add_phylopic_tree.R]:
```suggestion
#' @param tree `phylo`. The phylogenetic tree object on which to add the
```

File: R/add_phylopic_tree.R [hunk 3]
```diff
@@ -6,26 +6,35 @@
...
+#'   silhouette.
+#' @param tip The tip labels against which to add the silhouettes. If not
```
Comment (ms609) [inline R/add_phylopic_tree.R]:
```suggestion
#' @param tip `character`. The tip labels against which to add the silhouettes. If not
```

File: R/add_phylopic_tree.R [hunk 4]
```diff
@@ -6,26 +6,35 @@
...
+#'   If "NULL" and `height` is specified, the width is determined by the aspect
+#'   ratio of the original image. One of height and width must be "NULL".
+#' @param padding,relPadding Horizontal padding for each silhouette from it's
+#'   respective x value, in the plot coordinate system (`padding`) or relative
+#'   to the size of the plotting area (`relPadding`). Negative values offset to
+#'   the left.
+#' @param \dots Further arguments to pass to [add_phylopic_base()].
+#' @author [Martin R. Smith](https://orcid.org/0000-0001-5660-1727)
+#'   (<martin.smith@durham.ac.uk>)
+#' @seealso For trees plotted using \pkg{ggtree}, see [`geom_phylopic()`].
```
Comment (ms609) [inline R/add_phylopic_tree.R]: CRAN policies require the return value to be documented. We could add a note to the effect of "Called for its side effect of adding silhouettes to a plotted phylogenetic tree".

Strictly the function returns a call to `add_phylopic_base`, and I wasn't able to easily establish what that function returns – we should document that too.

Is there a structure to return values, e.g. returning `NULL` on failure?

File: R/add_phylopic_tree.R [hunk 5]
```diff
@@ -50,11 +59,13 @@ add_phylopic_tree <- function(tree, tip = names(img) %||% names(uuid) %||%
                                 names(name) %||% name,
                               img = NULL,
                               name = if (is.null(img) && is.null(uuid)) tip 
-                                else NULL, 
-                              uuid = NULL, width, padding = NULL,
+                                else NULL,
+                              uuid = NULL, align = "tip",
+                              width, padding = NULL,
                               relWidth = 0.06, relPadding = 1/200,
```
Comment (ms609) [inline R/add_phylopic_tree.R]: The problem with these defaults is that with `align = "plot"`, the silhouettes plot outwith the plotting area and are thus invisible!

If `align = "plot"`, it would be suitable to initialize `relPadding` to `-relWidth`.

We could go
```suggestion
                              relWidth = 0.06, relPadding = if(align == "tip") 1/200 else -relWidth,
```

Or we could set `relPadding = NULL` and include an `if.null(relPadding)` check in the function body, but I like surfacing the default value to the user, particularly in a case like this where the user is likely want to tweak the defaults (and thus to know where they started).

**Review by ms609 — CHANGES_REQUESTED** [review]
I've put this through its paces in a workflow I had to hand; the functionality looks good.  I've suggested a couple of tweaks to the docs, for consistency.  We also need to think about the default values for `align = "plot"`.

File: R/add_phylopic_tree.R (hunk 5 above)
Comment (willgearty) [reply R/add_phylopic_tree.R]: Oh geez, thanks for catching this @ms609! I've adapted your suggestion just a little bit by switching the `hjust` when `align = "plot"` and then only switching the sign of the `relPadding` value when `align = "plot"`. It effectively does the same thing as your suggestion, I believe, but it seems more user-friendly to me.

**Comment by willgearty** [comment]
Ah good idea, I've added that caveat and made an issue to add that functionality in a future release (#132). Thanks for your help with this!
